COLUMNS:
  TRANSACTION_ID: int64
  TX_DATETIME: object
  CUSTOMER_ID: int64
  TERMINAL_ID: int64
  TX_AMOUNT: float64
  TX_TIME_SECONDS: int64
  TX_TIME_DAYS: int64
  TX_FRAUD_SCENARIO: int64
  


TARGET_COLUMN:
  name: TX_FRAUD